FROM node:22.15

WORKDIR /app

COPY package*.json tsconfig*.json ./

RUN npm install
RUN npm install react-router-dom --save
RUN npm install --save-dev @types/node
RUN npm install -g serve

COPY . .

RUN npm run build
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
