# Build
FROM node:18-alpine AS build
WORKDIR /app

# CRA 경고 에러 방지
ENV CI=false

# 네이티브 모듈 대비(필요 없으면 지워도 됨)
RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm ci --no-audit --no-fund

COPY . .
RUN npm run build --loglevel verbose

# Serve (nginx)
FROM nginx:1.27-alpine
COPY --from=build /app/build /usr/share/nginx/html
