# Generated by Django 5.2.2 on 2025-08-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_name', models.CharField(max_length=50)),
                ('en_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_name', models.CharField(max_length=50)),
                ('en_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tier', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('search_keyword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_name', models.CharField(max_length=50)),
                ('en_name', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=20, null=True)),
                ('stage', models.CharField(blank=True, max_length=20, null=True)),
                ('vulnerable_properties', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/')),
                ('activation', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.category')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(default=0)),
                ('binding', models.BooleanField(default=False)),
                ('rest_gage', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.content')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('bundleCount', models.IntegerField(default=1)),
                ('trade_remain_count', models.CharField(max_length=50, null=True)),
                ('y_day_avg_price', models.FloatField()),
                ('recent_price', models.FloatField()),
                ('current_min_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItemAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('average_count', models.FloatField()),
                ('binding', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.content')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='items_conte_date_bca99b_idx')],
                'unique_together': {('content', 'item', 'binding', 'date')},
            },
        ),
    ]
