# Generated by Django 5.1.7 on 2025-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('stage_name', models.CharField(max_length=50)),
                ('stage_level', models.IntegerField()),
                ('entry_level', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('binding', models.CharField(max_length=10)),
            ],
        ),
    ]
