# Generated by Django 5.2.2 on 2025-08-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='search_keyword',
        ),
    ]
