# Generated by Django 5.2.2 on 2025-08-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_search_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitemaverage',
            name='created_at',
        ),
    ]
