# Generated by Django 5.2.2 on 2025-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_contentitemaverage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='stage',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
