# Generated by Django 5.2.2 on 2025-06-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='ko_name',
        ),
        migrations.AddField(
            model_name='category',
            name='en_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
