# Generated by Django 5.2.2 on 2025-06-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_name_category_ko_name_category_en_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_name', models.CharField(max_length=50)),
                ('en_name', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField()),
                ('vulnerable_properties', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gadians/')),
            ],
        ),
    ]
