# Generated by Django 5.2.2 on 2025-06-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_gadian'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadian',
            name='kind',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gadian',
            name='stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
