# Generated by Django 5.2.2 on 2025-07-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_gadian_kind_gadian_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadian',
            name='activation',
            field=models.BooleanField(default=True),
        ),
    ]
