# Generated by Django 5.2.2 on 2025-07-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_gadian_activation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='ko_neame',
        ),
        migrations.RemoveField(
            model_name='item',
            name='binding',
        ),
        migrations.RemoveField(
            model_name='item',
            name='entry_level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stage_level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stage_name',
        ),
        migrations.AddField(
            model_name='item',
            name='en_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tear',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
