# Generated by Django 5.2.2 on 2025-07-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GadianItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('binding', models.BooleanField(default=False)),
                ('gadian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.gadian')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
        ),
    ]
