# Generated by Django 5.2.2 on 2025-07-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_gadianitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadianitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gadianitem',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GadianItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('binding', models.BooleanField(default=False)),
                ('rest_gage', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Gadian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.gadian')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
        ),
    ]
