# Generated by Django 5.2.2 on 2025-07-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_gadianitem_created_at_alter_gadianitem_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ko_neame',
            new_name='ko_name',
        ),
        migrations.AlterField(
            model_name='gadianitemhistory',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gadianitemhistory',
            name='rest_gage',
            field=models.BooleanField(default=False),
        ),
    ]
