# Generated by Django 5.2.2 on 2025-07-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_rename_ko_neame_item_ko_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GadianItemAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_count', models.IntegerField()),
                ('binding', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('gadian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.gadian')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
        ),
        migrations.DeleteModel(
            name='GadianItem',
        ),
        migrations.AddIndex(
            model_name='gadianitemaverage',
            index=models.Index(fields=['date'], name='items_gadia_date_6389b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gadianitemaverage',
            unique_together={('gadian', 'item', 'binding', 'date')},
        ),
    ]
