# Generated by Django 5.2.2 on 2025-07-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_gadianitemaverage_delete_gadianitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('bundleCount', models.IntegerField(default=1)),
                ('trade_remain_count', models.CharField(max_length=50, null=True)),
                ('y_day_avg_price', models.FloatField()),
                ('recent_price', models.FloatField()),
                ('current_min_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
            ],
        ),
    ]
