# Generated by Django 5.2.2 on 2025-07-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadian',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.category'),
        ),
    ]
