# Generated by Django 5.2.2 on 2025-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_gadian_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadian',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
