# Generated by Django 5.2.2 on 2025-08-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_gadian_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='search_keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
